import { type InventoryType, type QualityType } from "@/legacy/types";

export const QUALITY_TYPES: QualityType[] = [
  { value: 1, label: "Poor", color: "#9D9D9D" },
  { value: 2, label: "Common", color: "#FFFFFF" },
  { value: 3, label: "Uncommon", color: "#1EFF00" },
  { value: 4, label: "Rare", color: "#0070DD" },
  { value: 5, label: "Epic", color: "#A335EE" },
  { value: 6, label: "Legendary", color: "#FF8000" },
];

export const INVENTORY_TYPES: InventoryType[] = [
  { value: "NON_EQUIP", label: "기타" },
  { value: "HEAD", label: "머리" },
  { value: "NECK", label: "목" },
  { value: "SHOULDER", label: "어깨" },
  { value: "CHEST", label: "가슴" },
  { value: "WAIST", label: "허리" },
  { value: "LEGS", label: "다리" },
  { value: "FEET", label: "발" },
  { value: "WRIST", label: "손목" },
  { value: "HAND", label: "장갑" },
  { value: "FINGER", label: "반지" },
  { value: "TRINKET", label: "장신구" },
  { value: "WEAPON", label: "무기" },
  { value: "SHIELD", label: "방패" },
  { value: "RANGED", label: "원거리" },
  { value: "CLOAK", label: "망토" },
];

export const EXPANSIONS = [
  { value: 11, label: "The War Within" },
  { value: 10, label: "Dragonflight" },
  { value: 9, label: "Shadowlands" },
  { value: 8, label: "Battle for Azeroth" },
  { value: 7, label: "Legion" },
  { value: 6, label: "Warlords of Draenor" },
  { value: 5, label: "Mists of Pandaria" },
  { value: 4, label: "Cataclysm" },
  { value: 3, label: "Wrath of the Lich King" },
  { value: 2, label: "The Burning Crusade" },
  { value: 1, label: "Vanilla" },
];

export const API_BASE_URL = "http://localhost:8080/api/v1";

// 아이템 클래스 데이터
export const ITEM_CLASSES = [
  { id: 0, name: "모든 아이템", icon: "📦" },
  {
    id: 2,
    name: "무기",
    icon: "⚔️",
    subclasses: [
      { id: 0, name: "모든 무기" },
      { id: 1, name: "도끼" },
      { id: 2, name: "활" },
      { id: 3, name: "총" },
      { id: 4, name: "단검" },
      { id: 5, name: "지팡이" },
      { id: 6, name: "둔기" },
      { id: 7, name: "창" },
      { id: 8, name: "마법봉" },
      { id: 9, name: "검" },
      { id: 10, name: "투척 무기" },
      { id: 11, name: "쌍수 무기" },
      { id: 13, name: "장거리 무기" },
      { id: 15, name: "다양한 무기" },
      { id: 16, name: "투척 무기" },
      { id: 18, name: "지팡이" },
      { id: 19, name: "지팡이" },
      { id: 20, name: "지팡이" },
    ],
  },
  {
    id: 4,
    name: "방어구",
    icon: "🛡️",
    subclasses: [
      { id: 0, name: "모든 방어구" },
      { id: 1, name: "천" },
      { id: 2, name: "가죽" },
      { id: 3, name: "사슬" },
      { id: 4, name: "판금" },
      { id: 5, name: "방패" },
      { id: 6, name: "방패" },
      { id: 7, name: "방패" },
      { id: 8, name: "방패" },
    ],
  },
  {
    id: 9,
    name: "장신구",
    icon: "💍",
    subclasses: [
      { id: 0, name: "모든 장신구" },
      { id: 1, name: "반지" },
      { id: 2, name: "장신구" },
      { id: 3, name: "장신구" },
      { id: 4, name: "장신구" },
      { id: 5, name: "장신구" },
      { id: 6, name: "장신구" },
      { id: 7, name: "장신구" },
      { id: 8, name: "장신구" },
      { id: 9, name: "장신구" },
      { id: 10, name: "장신구" },
      { id: 11, name: "장신구" },
      { id: 12, name: "장신구" },
      { id: 13, name: "장신구" },
      { id: 14, name: "장신구" },
      { id: 15, name: "장신구" },
      { id: 16, name: "장신구" },
      { id: 17, name: "장신구" },
      { id: 18, name: "장신구" },
      { id: 19, name: "장신구" },
      { id: 20, name: "장신구" },
      { id: 21, name: "장신구" },
      { id: 22, name: "장신구" },
      { id: 23, name: "장신구" },
    ],
  },
  {
    id: 15,
    name: "기타",
    icon: "🎒",
    subclasses: [
      { id: 0, name: "모든 기타" },
      { id: 1, name: "가방" },
      { id: 2, name: "소모품" },
      { id: 3, name: "음식" },
      { id: 4, name: "음료" },
      { id: 5, name: "연금술" },
      { id: 6, name: "연금술" },
      { id: 7, name: "연금술" },
      { id: 8, name: "연금술" },
      { id: 9, name: "연금술" },
      { id: 10, name: "연금술" },
      { id: 11, name: "연금술" },
      { id: 12, name: "연금술" },
      { id: 13, name: "연금술" },
      { id: 14, name: "연금술" },
      { id: 15, name: "연금술" },
      { id: 16, name: "연금술" },
      { id: 17, name: "연금술" },
      { id: 18, name: "연금술" },
      { id: 19, name: "연금술" },
      { id: 20, name: "연금술" },
      { id: 21, name: "연금술" },
      { id: 22, name: "연금술" },
      { id: 23, name: "연금술" },
    ],
  },
];
