import "@/styles/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Script from "next/script";
import { type AFC, type PropsWithChildren } from "react";

const primaryFont = localFont({
  variable: "--font-primary",
  src: "../../../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: AFC<PropsWithChildren> = async ({ children }) => {
  return (
    <html lang="en">
      <Script id="wh-init" strategy="beforeInteractive">
        {`
            var whTooltips = {
              colorLinks: true,
              iconizeLinks: true,
              iconSize: 'large',
              renameLinks: true,
            };
        `}
      </Script>
      <Script src="https://wow.zamimg.com/js/tooltips.js" />

      <body className={`${primaryFont.variable} antialiased`}>{children}</body>
    </html>
  );
};

export default RootLayout;
