import "@/styles/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { type AFC, type PropsWithChildren } from "react";

const primaryFont = localFont({
  variable: "--font-primary",
  src: "../../../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: AFC<PropsWithChildren> = async ({ children }) => {
  return (
    <html lang="en">
      <body className={`${primaryFont.variable} antialiased`}>{children}</body>
    </html>
  );
};

export default RootLayout;
